// Generated by CoffeeScript 1.10.0
(function() {
  window.custom || (window.custom = {});

  window.custom.hello = function() {
    return alert("Hello");
  };

  window.custom.square1 = function(x) {
    return alert(x * x);
  };

  window.custom.fill = function(container, liquid) {
    if (container == null) {
      container = "Baskit";
    }
    if (liquid == null) {
      liquid = "water";
    }
    return alert("Fill  " + container + " with " + liquid + "..");
  };

  window.custom.condition = function(container) {
    if (container != null) {
      return alert("Container is  " + container + " ");
    } else {
      return alert("Container is not define ");
    }
  };

}).call(this);
